name: Run Checks
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
          token: GITHUB_TOKEN
      - name: Set up Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm ci 
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
      - name: Install closeure compiler
        run: npm i -g google-closure-compiler
      - name: Run closure compiler
        run: echo "::set-output name=compile::$(google-closure-compiler --js ./src/pwamp.js --js_output_file pwamp.compiled.js)"
        id: pwamp-closure-compiler
      # - id: files
      #   uses: jitterbit/get-changed-files@v1
      #   with:
      #     # Format of the steps output context.
      #     # Can be 'space-delimited', 'csv', or 'json'.
      #     #
      #     # Default: 'space-delimited'
      #     format: 'json'
      # - name: Format Msg
      #   uses: ./.github/actions/google-chat-notification-on-push/
      #   with:
      #     event: "${{toJSON(github.event)}}"
      #     steps: "${{toJSON(steps)}}"
      #   id: modded
      - name: Dev Output
        run: |
          echo "${{github.event}}"
      # - name: Send Google Chat Notification
      #   run: |
      #     curl --location --request POST 'https://chat.googleapis.com/v1/spaces/AAAA72wbnqo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=1iD1-r6ibCBa3VbHdTzYLMp-exJU70e_J0__XvWXQSA%3D' \
      #     --header 'Content-Type: application/json' \
      #     -d ${{steps.modded.outputs.chat-msg}}
